// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelChallengeBot.EF;

#nullable disable

namespace ModelChallengeBot.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20220117021647_challengeupdate")]
    partial class challengeupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("ModelChallengeBot.EF.Models.ChannelRegistry", b =>
                {
                    b.Property<int>("ChannelRegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RegisterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelRegistryId");

                    b.ToTable("ChannelRegistry");
                });

            modelBuilder.Entity("ModelChallengeBot.EF.Models.RoleRegistry", b =>
                {
                    b.Property<int>("RoleRegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RegisterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleRegistryId");

                    b.ToTable("RoleRegistry");
                });
#pragma warning restore 612, 618
        }
    }
}
